#!/bin/bash
####################    While     #######################

echo "While"
a=0 
while [ $a -lt 10 ]
do
   echo $a
   if [ $a -eq 5 ]
   then
       break
   fi
   a=`expr $a + 1`
done

for var1 in 1 2 3
do
   for var2 in 0 5
   do
	if [ $var1 -eq 2 -a $var2 -eq 0 ]
	then
	   break 2
	else
	   echo "$var1 $var2"
	fi
   done
done

nums="1 2 3 4 5 6 7 8 9"
for num in $nums
do
	x=`expr $num % 2`
	if [ $x -eq 0 ]
	then
		echo "Number is an even number !!  $num"
		continue
	fi
	echo "Found odd number $num"
done





