#!/bin/bash

sayi=$1
i=0
j=0
sayac=0
for ((i=2;i<=sayi;i++))
do
	for ((j=2;j<i;j++ ))
	do
		if ((i%j==0))
		then
		  ((sayac++))
		fi
	done
	if ((sayac==0 ))
	then
	echo "$i sayısı ASAL"
	else
	echo "$i sayısı ASAL DEGİL"
	fi
	sayac=0
done

