#!/bin/bash
`ps aux | cut -c1-100 >process`
file="process"
deger=0.0
while read  line
do
	dizi=($line)
	cpu=${dizi[2]}
	if [[ $cpu != "%CPU" ]]
	then
		durum=`echo "$cpu > $deger" | bc `
		if [[ $durum -eq 1 ]]
		then
			deger=$cpu
			islem=$line
		fi
	fi
done <$file
echo "CPU $islem..."
echo $deger
