#!/bin/bash

echo "------------POLİNDROM SAYI --------------"
echo "Enter a String : "
read string
 
i=0
len=${#string}
 
mid=$(($len/2))
 
while [ $i -lt $mid ]
  do
    if [ "${string:$i:1}" != "${string: $(($i+1)):1}" ]
      then
      echo "\"$string\" IS NOT a Palindrome"
      exit
    fi
    (( i++))
done
echo "\"$string\" IS a Palindrome"
